version: "3.8"

services:
  sphinx-frontend:
    build: 
      context: ./sphinx-frontend
      args:
        - API_SERVER_ADDRESS=sphinx-backend
    ports:
      - 5555:5555
    networks:
      - sphinx-net
    depends_on:
      - sphinx-backend

  sphinx-backend:
    build: ./sphinx-backend
    ports:
      - 5000:5000
    networks:
      - sphinx-net

networks:
  sphinx-net: