version: "3.8"

services:
  sphinx-frontend:
    build: ./sphinx-frontend
    ports:
      - 5555:5555
    networks:
      - sphinx-net

  sphinx-backend:
    build: ./sphinx-backend
    ports:
      - 5000:5000
    networks:
      - sphinx-net

networks:
  sphinx-net: